<script lang="ts">
  import DiceButton from "~/components/DiceButton.svelte";
  import Divider from "~/components/Divider.svelte";
  import { AdviceApiResponse } from "~/types/customTypes";

  let adviceText: string;
  let adviceNumber: string;

  const fetchAdvice = async (): Promise<AdviceApiResponse> => {
    const url = "https://api.adviceslip.com/advice";
    return await fetch(url).then((response) => response.json());
  };

  const setAdvice = async (): Promise<void> => {
    const { slip } = await fetchAdvice();
    adviceText = slip.advice;
    adviceNumber = slip.id;
  };

  setAdvice();
</script>

<section class="card">
  <h1 class="advice-number">Advice #{adviceNumber}</h1>
  {#key adviceNumber}
    <p class="quote text-focus-in">
      {adviceText}
    </p>
  {/key}
  <div class="divider-wrapper">
    <Divider />
  </div>
  <div class="dice-button-wrapper">
    <DiceButton onClick={setAdvice} />
  </div>
</section>

<style>
  .card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 100%;
    gap: 24px;
    padding: 0 24px;
    border-radius: 10px;
    background-color: var(--dark-grayish-blue);
    text-align: center;
  }

  .advice-number {
    margin-top: 40px;

    font-size: 11px;
    line-height: 15px;
    letter-spacing: 3.4571425914764404px;
    text-transform: uppercase;
    color: var(--neon-green);
  }

  .quote {
    font-family: Manrope;
    font-size: 24px;
    font-weight: 800;
    line-height: 33px;
    letter-spacing: -0.2571428716182709px;
  }

  .divider-wrapper {
    margin-bottom: 64px;
  }

  .dice-button-wrapper {
    position: absolute;
    bottom: -32px;
    margin: 0 auto;
    left: calc(50% - 32px);
  }

  /* Text Animation */
  .text-focus-in {
    -webkit-animation: text-focus-in 1s cubic-bezier(0.55, 0.085, 0.68, 0.53)
      both;
    animation: text-focus-in 1s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2022-7-30 17:48:18
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
  @-webkit-keyframes text-focus-in {
    0% {
      -webkit-filter: blur(12px);
      filter: blur(12px);
      opacity: 0;
    }
    100% {
      -webkit-filter: blur(0px);
      filter: blur(0px);
      opacity: 1;
    }
  }
  @keyframes text-focus-in {
    0% {
      -webkit-filter: blur(12px);
      filter: blur(12px);
      opacity: 0;
    }
    100% {
      -webkit-filter: blur(0px);
      filter: blur(0px);
      opacity: 1;
    }
  }

  /* Breakpoints */

  @media (min-width: 768px) {
    .advice-number {
      margin-top: 48px;

      font-size: 13px;
      line-height: 18px;
      letter-spacing: 4.085713863372803px;
      text-align: center;

      color: var(--neon-green);
    }

    .quote {
      font-size: 28px;
      line-height: 38px;
      letter-spacing: -0.30000001192092896px;
    }

    .divider-wrapper {
      margin-bottom: 72px;
    }
  }
</style>
